### ISSUE TITLE
How to retrieve bitmap into non-static ImageView?

### ISSUE THREAD

**Issue by power7714** [wseemann/FFmpegMediaMetadataRetriever-ListExample#1]
Hey @wseemann, Thank you for answering my question in the other repository and creating this sample project. Greatly appreciate it!

After looking over your example, I have an issue. How would I retrieve that bitmap into a non-static ImageView? I am using the following library to display the video within a ListView that has different items in each row.
[JieCaoVideoPlayer](https://github.com/lipangit/JieCaoVideoPlayer)
to set the thumbnail for the video, I have to load the bitmap into the player with the following code:
`holder.postVideoThumb.thumbImageView.setImageBitmap(videoThumbnail);`

Where `JCVideoPlayerStandard postVideoThumb` is the variable. 

Any ideas?

**Comment by wseemann** [comment]
@power7714 is `thumbImageView` a subclass of `ImageView`? If so, just modify my `RecyclerAdapter` to pass `holder.postVideoThumb.thumbImageView` to the `AsyncTask` that does the image retrieval.

**Comment by power7714** [comment]
@wseemann Yes it is. I tried what you said and it works. Thank you! On a quick sidenote, could I use the same handler to get the video duration metadata from the remote video?

**Comment by wseemann** [comment]
@power7714 Yes, modify the object being sent to the handler to include a `String` field that will contain the duration.
